name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      # Build with Gradle
#      - name: Build with Gradle
#        run: ./gradlew clean build

#      # Run tests and generate JaCoCo coverage report
#      - name: Test with Gradle
#        run: ./gradlew test

      # Download and set up SonarScanner
      - name: Download SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner

      # Configure SonarScanner properties
      - name: Configure SonarScanner
        run: |
          echo "sonar.host.url=${{ secrets.SONAR_TOKEN }}" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.token=${{ secrets.SONAR_TOKEN }}" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.organization=desapp_grupo_d" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.projectKey=PeMendez_unq_desapp_grupo_d" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.projectName=CryptoExchange" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.sources=src/main/" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.tests=src/test/" >> sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.coverage.jacoco.xmlReportPaths=build/jacocoReportDir/test/jacocoTestReport.xml" >> sonar-scanner/conf/sonar-scanner.properties

      # Run SonarScanner
      - name: Run SonarScanner
        run: sonar-scanner/bin/sonar-scanner