name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build


      - name: Run tests with Gradle
        run: ./gradlew test